### ISSUE TITLE
Please add a screen shot to the readme

### ISSUE THREAD

**Issue by unixorn** [nescalante/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by nescalante** [comment]
sure!
is this screenshot ok for you?

![image](https://user-images.githubusercontent.com/2078803/48909035-e8787880-ee4a-11e8-8497-34dca0801b81.png)

already added to the readme

**Comment by unixorn** [comment]
Thanks! There must have been a render issue,  I didn't see the screen shot.

I'm going to add it as nescalante - zsh-theme is a bit generic :-)

**Comment by nescalante** [comment]
do you see it in the readme?

**Comment by unixorn** [comment]
Yes, I see it in the readme now, and I've added it to the list, thanks!
